# chain-tx

dependency with chainlibpy version 1.0.0

> Tools for [Crypto.com](https://github.com/crypto-com/chain-main) crossfire event to generate mass transfert over time

## Usage<a name="usage"></a>

### setup your wallet

Modify the [seed](https://github.com/Galadrin/chain-tx/blob/master/transaction.py#L94) with the one of you wallet
Modify the [delegatorAddr](https://github.com/Galadrin/chain-tx/blob/master/transaction.py#L99) with you own validator

### generate transactions

The script generate transactions by offline signing and sending through the RPC api endpoint.
the Tx are generated by batch of 300

a loop of software does the following steps :
 - rerieve the sequence number and the balance
 - for a loop of 300 Tx
   - generate Tx
   - sent Tx
 - wait for 5 seconds
 
### errors

3 errors codes are managed :
- 0 : The Tx have been added successfully in the mempool
  * increment the sequence number and go forward
- 4 : Tx signature verification failure
  * wait 5 seconds then break the for-loop
- 19 : the same Tx already exist in the mempool
  caused by : sequence number return at loop startup is not up to date.
  * break the for-loop
- 20 : the mempool is full
  * wait 1 second and break the for-loop
- 32 : sequence number don't match
